# Site settings
name: Dodi Rivaldi
title: Dodi Rivaldi | Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://dodirivaldi.github.io/
baseurl: ''
email: dodirivaldi64@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://image.flaticon.com/icons/svg/2282/2282188.svg
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:dodirivaldi64@gmail.com
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/dodi.rivaldi
  - title: github
    url: https://github.com/dodirivaldi
  - title: linkedin
    url: https://www.linkedin.com/in/dodirivaldi/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
